14

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -28,20 +28,20 @@ jobs:
           port: 22
           key: ${{ secrets.SSH_KEY }}
           script: |
-            # Создаём папку для проекта
             mkdir -p ~/devops-go-app
             cd ~/devops-go-app
 
-            # Обновляем код или клонируем
             if [ -d ".git" ]; then
               git pull
             else
               git clone https://github.com/sonnyranger/devops-go-app .
             fi
 
-            # Строим и поднимаем контейнеры через Docker Compose V2
-            docker compose build
-            docker compose up -d
-
-            # Выводим статус контейнеров для проверки
-            docker compose ps
+            # Проверяем Docker Compose V2 и деплой
+            if docker compose version > /dev/null 2>&1; then
+              docker compose up --build --detach
+              docker compose ps
+            else
+              echo "Error: Docker Compose V2 not found"
+              exit 1
+            fi
